sections:

  - name: "Main"
    valid_minutes:
      - 0
      - 30
    rows:
      - row: 1
        places: 45
      - row: 2
        places: 46
      - row: 3
        places: 46
      - row: 4
        places: 46
      - row: 5
        places: 46
      - row: 6
        places: 41

  - name: "Snarksalen"
    valid_minutes:
      - 0
      - 30
    rows:
      - row: 1
        places: 13
      - row: 2
        places: 10
      - row: 3
        places: 10
      - row: 4
        places: 10
      - row: 5
        places: 10
      - row: 6
        places: 10
      - row: 7
        places: 9

  - name: "Tysk avdelning"
    valid_minutes:
      - 0
      - 30
    rows:
      - row: 1
        places: 15
      - row: 2
        places: 10
      - row: 3
        places: 10
      - row: 4
        places: 10
      - row: 5
        places: 10
      - row: 6
        places: 10
      - row: 7
        places: 12
